#name: HelloWorldWorkflow
# 'on':
#   github:
#     branches:
#       only: main
on:
  push:
    branches:
      - main
jobs:
  HelloWorld:
    runs-on: CPU
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
